frictionlessdata/livemark

README.md, index.md
Hi @roll! Here are my copyedits for livemark text. Thanks!
=> edits text for clarity

index.html, index.md, livemark/assets/templates/content.css, livemark/assets/templates/content.html, livemark/assets/templates/layout.html, livemark/assets/templates/scroll.html, livemark/assets/templates/sidebar.css, livemark/assets/templates/sidebar.html, livemark/assets/templates/sidebar.js, livemark/document.py, livemark/renderer.py
=> Improved sidebar feature

index.html, index.md, livemark/assets/templates/features/header.html, livemark/assets/templates/features/navigation.html, livemark/assets/templates/features/reference.html, livemark/assets/templates/features/scroll.html, livemark/assets/templates/features/status.html, livemark/assets/templates/layout.html, livemark/assets/templates/sections/content.html, livemark/assets/templates/sections/left.html, livemark/assets/templates/sections/main.html, livemark/assets/templates/sections/right.html, livemark/assets/templates/sections/sidebar.html
=> Rebased on 3 columns

index.html, index.md, livemark/assets/templates/features/about.html, livemark/assets/templates/features/status.html, livemark/assets/templates/features/time.html, livemark/assets/templates/layout.html, livemark/assets/templates/sections/main.html, livemark/document.py
=> Implemented time feature

index.html, index.md, livemark.yaml, livemark/document.py, setup.py
=> Support livemark.yaml

index.html, livemark/assets/profiles/config.json, livemark/config.py, livemark/document.py, setup.py
=> Added jsonschema validation

index.html, index.md
Looking at the README and running the suggested commands in the README I get an exception straight away:
```
livemark build '<path=index.md>'
Traceback (most recent call last):
File "/home/adria/.local/bin/livemark", line 8, in <module>
sys.exit(program())
File "/home/adria/.local/pipx/venvs/livemark/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
return get_command(self)(*args, **kwargs)
File "/home/adria/.local/pipx/venvs/livemark/lib/python3.8/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/home/adria/.local/pipx/venvs/livemark/lib/python3.8/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/home/adria/.local/pipx/venvs/livemark/lib/python3.8/site-packages/click/core.py", line 1259, in invoke …
```
=> Tweak install instructions

docs/configuration.html, docs/configuration.md, docs/getting-started.html, docs/getting-started.md, index.md, livemark.yaml, livemark/assets/templates/features/header.html, livemark/assets/templates/features/pages.html, livemark/config.py, livemark/document.py
=> Added pages feature

setup.py
=> Pin major frictionless version

docs/configuration.html, docs/getting-started.html, index.html, livemark.yaml, livemark/assets/profiles/config.json, livemark/assets/templates/features/header.html, livemark/assets/templates/features/navigation.html, livemark/assets/templates/features/time.html, livemark/document.py
=> Ability to enable feature with on conf

docs/configuration.html, docs/getting-started.html, index.html, livemark.yaml, livemark/assets/templates/features/analytics.html, livemark/config.py
=> Added analytics feature

docs/configuration.html, docs/getting-started.html, index.html, livemark/assets/templates/sections/left.html, livemark/assets/templates/sections/right.html
=> Add scrolling to columns on overflow

docs/configuration.html, docs/getting-started.html, index.html, livemark.yaml, livemark/assets/templates/features/readability.html, livemark/assets/templates/features/scroll.html, livemark/assets/templates/sections/base.html, livemark/assets/templates/sections/main.html, livemark/config.py
=> Implement the readability feature

Makefile, livemark/document.py, livemark/markdown.py, livemark/program.py, livemark/renderer.py
=> Implemented `livemark sync` (goodread merge)

docs/getting-started.html, index.html, livemark/document.py, livemark/markup.py, livemark/plugin.py, livemark/program/build.py, livemark/program/start.py, tests/test_document.py
=> Implemented watch mode for pages

docs/configuration.html, docs/getting-started.html, index.html, livemark.yaml, livemark/plugins/controls/style.css, livemark/plugins/html/style.css, livemark/plugins/mobile/__init__.py, livemark/plugins/mobile/markup.html, livemark/plugins/mobile/plugin.py, livemark/plugins/mobile/script.js, livemark/plugins/mobile/style.css, livemark/plugins/stats/script.js, livemark/plugins/stats/style.css, livemark/program/build.py
=> Implemented MobilePlugin

livemark/plugins/html/renderer.py, livemark/plugins/pages/plugin.py, livemark/program/merge.py, livemark/server.py, livemark/settings.py
=> Implemented live doc writing

index.html, livemark/helpers.py, livemark/plugin.py, livemark/plugins/chart/plugin.py, livemark/plugins/script/plugin.py, livemark/plugins/table/plugin.py, tests/test_snippet.py
=> Implemented script caching

data/diff.md, data/invalid.md, data/preface.md, index.html, livemark/document.py, livemark/helpers.py, livemark/markup.py, livemark/program/build.py, livemark/program/merge.py, livemark/system.py, tests/program/test_build.py, tests/program/test_main.py, tests/program/test_merge.py, tests/test_document.py, tests/test_markup.py, tests/test_snippet.py, tests/test_system.py
=> Improved test coverage

404.html, 404.md, blog/2021-09-01-meet-livemark.html, blog/index.html, docs/configuration.html, docs/installation.html, docs/livemark-components.html, docs/livemark-markdown.html, docs/universe.html, index.html, livemark.yaml, livemark/plugins/redirect/__init__.py, livemark/plugins/redirect/missing.md, livemark/plugins/redirect/plugin.py, livemark/plugins/search/plugin.py
=> Implemented RedirectPlugin

.livemark/cards/test.html, 404.html, blog/2021-09-01-meet-livemark.html, blog/index.html, cards/plugin.html, docs/configuration.html, docs/installation.html, docs/livemark-components.html, docs/livemark-markdown.html, docs/plugin-system.html, docs/universe.html, docs/universe.md, index.html, livemark/config.py, livemark/document.py, livemark/helpers.py, livemark/plugin.py, livemark/plugins/about/plugin.py, livemark/plugins/cards/__init__.py, livemark/plugins/cards/markup.html, livemark/plugins/cards/plugin.py, livemark/plugins/cards/script.js, livemark/plugins/cards/style.css, livemark/plugins/logic/plugin.py, livemark/project.py, tests/test_document.py
=> Implemented CardsPlugin

404.html, blog/2021-09-01-meet-livemark.html, blog/index.html, docs/configuration.html, docs/installation.html, docs/livemark-components.html, docs/livemark-markdown.html, docs/plugin-system.html, docs/universe.html, docs/universe.md, index.html, livemark/config.py, livemark/document.py, livemark/plugin.py, livemark/plugins/audio/__init__.py, livemark/plugins/audio/markup.html, livemark/plugins/audio/plugin.py, livemark/plugins/audio/style.css, livemark/project.py, setup.py
=> Implemented audio plugin

404.html, blog/2021-09-01-meet-livemark.html, blog/index.html, docs/configuration.html, docs/installation.html, docs/livemark-components.html, docs/livemark-markdown.html, docs/plugin-system.html, docs/universe.html, index.html, livemark/plugins/display/script.js, livemark/plugins/pagination/plugin.py, livemark/plugins/pagination/script.js
=> Remember readability setting

404.html, blog/2021-09-01-meet-livemark.html, blog/index.html, docs/configuration.html, docs/forum.html, docs/forum.md, docs/livemark-components.html, docs/livemark-markdown.html, docs/plugin-system.html, docs/universe.html, index.html, livemark.yaml, livemark/plugins/comments/__init__.py, livemark/plugins/comments/markup.html, livemark/plugins/comments/plugin.py, livemark/plugins/comments/script.js, livemark/plugins/comments/style.css
=> Implemented CommentPlugin

404.html, blog/2021-09-01-meet-livemark.html, blog/index.html, docs/configuration.html, docs/forum.html, docs/installation.html, docs/livemark-components.html, docs/livemark-components.md, docs/livemark-markdown.html, docs/plugin-system.html, docs/universe.html, index.html, livemark/plugins/markup/markup.html, livemark/plugins/markup/plugin.py, livemark/plugins/script/plugin.py
=> Added JSX support to MarkupPlugin

pages/guides-and-tutorials/data-journalism.md
There is a small typo
---
Please preserve this line to notify @roll (lead of this repository)
=> a small typo

livemark/plugins/display/markup.html
=> Change the "Print" button have "Decrease readability" as pop-up
